services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: ["sh", "-c", "cd ./apps/api && npx drizzle-kit migrate && npm run dev"]
    environment:
      - NODE_ENV=development
      - DATABASE_URL=/app/data/sqlite.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s